//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.AdditionProdutForProducts = new HashSet<AdditionProdutForProduct>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.ProductIngridients = new HashSet<ProductIngridient>();
        }
    
        public int ProductId { get; set; }
        public int CategoryId { get; set; }
        public string NameRus { get; set; }
        public string NameUkr { get; set; }
        public int NamberOfOrders { get; set; }
        public Nullable<int> Count { get; set; }
        public int Energy { get; set; }
        public int Balance { get; set; }
        public decimal Price { get; set; }
        public bool Sale { get; set; }
        public System.DateTime AddDate { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual ICollection<AdditionProdutForProduct> AdditionProdutForProducts { get; set; }
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual ICollection<ProductIngridient> ProductIngridients { get; set; }
        public virtual ProductWeightDetail ProductWeightDetail { get; set; }
    }
}
