//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication3
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductWeightDetail
    {
        public int ProductId { get; set; }
        public string Name { get; set; }
        public decimal Vaule { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
